name: Actualizar Noticias Deportivas

on:
  schedule:
    - cron: '0 * * * *' # Se ejecuta cada hora
  workflow_dispatch:      # Permite ejecutarlo manualmente para probar

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar script de actualización
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }} # Conexión con tu Secret
        run: python actualizar_noticias.py

      - name: Guardar cambios
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualización automática de noticias con NewsAPI"
