name: Actualizar Noticias Deportivas

on:
  schedule:
    - cron: '0 * * * *' # Se ejecuta cada hora
  workflow_dispatch:      # Permite ejecutarlo manualmente para probar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: [actions/checkout](https://github.com)@v4

      - name: Configurar Python
        uses: [actions/setup-python](https://github.com)@v5
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar script de actualización
        run: python actualizar_noticias.py

      - name: Guardar cambios en GitHub
        uses: [stefanzweifel/git-auto-commit-action](https://github.com)@v5
        with:
          commit_message: "Actualización automática de noticias"
